### ISSUE TITLE
Keep channels async when changing volume from buttons

### ISSUE THREAD

**Issue by PGayol** [saumya-banthia/volume-boost#3]
Hi!

Great plugin. My Deck seems to have a volume difference between right and left speaker, so I'm using the plugin to individually adjust the volume of each channel separately and "compensate" that difference.

But as soon as I adjust the volume using the console's physical volume buttons, the configuration is reset, so the difference between both speakers is noticeable again.

Is there any way to keep the relative difference between both channels, even when adjusting volume from physical buttons?

Thanks!

**Comment by saumya-banthia** [comment]
Hi @PGayol this is within expected behavior. It's mentioned in the README for this repo as well.

As per my knowledge, volume buttons generally are programmed at the hardware level - which is why it leads me to think plugins wouldn't be able to change their behavior, if you do find a way to, I'll be happy to learn something new as well.

**Comment by saumya-banthia** [comment]
Closing.

**Comment by PGayol** [comment]
Thanks for your answer @saumya-banthia. Didn't know about the way volume buttons worked, so wasn't sure about the feasibility of my request. I will keep an eye on it anyway. Regards!
